[package]
name = "lethal_potato"
version = "0.1.0"
authors = ["liquidlegs"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.22", features = ["derive"] }
console = "0.15.4"
